version: 1.0.{build}
image: Visual Studio 2017
install:
- ps: Install-Product node 6

before_build:
- yarn

build_script:
- yarn build

test_script:
- yarn test

after_test:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\junit.xml))
